import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Nav from "../components/Nav";
import Intro from "../components/Intro";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>HOLA NFT</title>
        <meta name="description" content="Generated by HolaMetaverso" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <Intro />
      <Footer />
    </div>
  );
}
